version: '3.8'

services:
  mwave-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - mwave-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mwave-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mwave-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - mwave-network

networks:
  mwave-network:
    driver: bridge

volumes:
  grafana-storage: 